version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://user-dashboard-frontend/
      # - aws cloudfront create-invalidation --distribution-id <distribution-id> --paths "/*"
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
  